package net.labymod.autogen.api.lss;

import java.util.Map;
import net.labymod.api.client.chat.advanced.ChatMessagesWidget;
import net.labymod.api.client.gui.lss.property.DirectPropertyValueAccessor;
import net.labymod.api.client.gui.lss.property.DirectPropertyValueAccessorRegisterBulk;
import net.labymod.api.client.gui.screen.widget.AbstractWidget;
import net.labymod.api.client.gui.screen.widget.SimpleWidget;
import net.labymod.api.client.gui.screen.widget.StyledWidget;
import net.labymod.api.client.gui.screen.widget.Widget;
import net.labymod.api.client.gui.screen.widget.WrappedWidget;
import net.labymod.api.client.gui.screen.widget.widgets.ComponentWidget;
import net.labymod.api.client.gui.screen.widget.widgets.DivWidget;
import net.labymod.api.client.gui.screen.widget.widgets.MarkdownWidget;
import net.labymod.api.client.gui.screen.widget.widgets.ModelWidget;
import net.labymod.api.client.gui.screen.widget.widgets.PopupWidget;
import net.labymod.api.client.gui.screen.widget.widgets.RatingWidget;
import net.labymod.api.client.gui.screen.widget.widgets.WheelWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.Document;
import net.labymod.api.client.gui.screen.widget.widgets.activity.chat.ChatButtonWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.chat.ChatLineWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.chat.ChatTabWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.multiplayer.LiveServerInfoWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.multiplayer.SelectionWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.multiplayer.ServerEntryWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.multiplayer.ServerInfoWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.multiplayer.ServerListWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.settings.ActivitySettingWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.settings.AddonActivityWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.settings.CategoryWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.settings.CollectionResetWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.settings.SettingOpenActivityWidget;
import net.labymod.api.client.gui.screen.widget.widgets.activity.settings.SettingWidget;
import net.labymod.api.client.gui.screen.widget.widgets.context.ContextMenuEntryWidget;
import net.labymod.api.client.gui.screen.widget.widgets.context.ContextMenuListWidget;
import net.labymod.api.client.gui.screen.widget.widgets.hud.HudWidgetWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.AdvancedSelectionWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.ButtonWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.CheckBoxWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.FileChooserWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.KeybindWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.MultiKeybindWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.NumberTextFieldWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.SimpleButtonWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.SliderWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.SwitchWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.TagInputWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.TextFieldWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.WidgetFieldWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.ColorPickerWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.ColorPickerInputWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.ColorPickerInputWrapperWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.ColorPickerOverlayWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.ColorPickerPlateWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.ColorPickerSelectorWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.selector.AlphaSelectorWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.selector.HueSelectorWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.selector.MarkerWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.selector.SelectorWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.color.overlay.selector.ShadeSelectorWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.dropdown.DropdownWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.dropdown.popup.DropdownEntryWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.dropdown.popup.DropdownListWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.dropdown.popup.DropdownPopupWidget;
import net.labymod.api.client.gui.screen.widget.widgets.input.itemstack.ItemStackPickerWidget;
import net.labymod.api.client.gui.screen.widget.widgets.labyconnect.chat.attachment.AttachmentWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.FlexibleContentWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.FoldingWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.GridWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.IconSliderWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.LabeledWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.ScrollWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.ScrollbarWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.SplitContentWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.TilesGridFeedWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.TilesGridWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.TreeWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.entry.FlexibleContentEntry;
import net.labymod.api.client.gui.screen.widget.widgets.layout.entry.HorizontalListEntry;
import net.labymod.api.client.gui.screen.widget.widgets.layout.entry.TileWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.grid.LazyGridFeedWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.grid.LazyGridWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.HorizontalListWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.ListWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.SessionedListWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.VerticalListWidget;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.WrappedListWidget;
import net.labymod.api.client.gui.screen.widget.widgets.minecraft.FireWidget;
import net.labymod.api.client.gui.screen.widget.widgets.minecraft.ItemStackWidget;
import net.labymod.api.client.gui.screen.widget.widgets.minecraft.entity.EntityWidget;
import net.labymod.api.client.gui.screen.widget.widgets.minecraft.entity.HealthStatusWidget;
import net.labymod.api.client.gui.screen.widget.widgets.navigation.NavigationElementWidget;
import net.labymod.api.client.gui.screen.widget.widgets.navigation.PageWidget;
import net.labymod.api.client.gui.screen.widget.widgets.navigation.TabLayoutWidget;
import net.labymod.api.client.gui.screen.widget.widgets.navigation.TabWidget;
import net.labymod.api.client.gui.screen.widget.widgets.overlay.OverlayWidget;
import net.labymod.api.client.gui.screen.widget.widgets.popup.AdvancedPopupWidget;
import net.labymod.api.client.gui.screen.widget.widgets.renderer.HrWidget;
import net.labymod.api.client.gui.screen.widget.widgets.renderer.IconWidget;
import net.labymod.api.client.gui.screen.widget.widgets.renderer.ProgressBarWidget;
import net.labymod.api.client.gui.screen.widget.widgets.renderer.ProgressableProgressBarWidget;
import net.labymod.api.client.gui.screen.widget.widgets.renderer.ScreenRendererWidget;
import net.labymod.api.client.gui.screen.widget.widgets.renderer.VariableIconWidget;
import net.labymod.api.client.gui.screen.widget.widgets.transform.FadingWidget;
import net.labymod.api.client.gui.screen.widget.widgets.transform.InterpolateWidget;
import net.labymod.autogen.api.lss.properties.direct.AbstractWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ActivitySettingWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.AddonActivityWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.AdvancedPopupWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.AdvancedSelectionWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.AlphaSelectorWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.AttachmentWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ButtonWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.CategoryWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ChatButtonWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ChatLineWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ChatMessagesWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ChatTabWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.CheckBoxWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.CollectionResetWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ColorPickerInputWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ColorPickerInputWrapperWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ColorPickerOverlayWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ColorPickerPlateWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ColorPickerSelectorWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ColorPickerWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ComponentWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ContextMenuEntryWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ContextMenuListWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.DivWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.DocumentDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.DropdownEntryWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.DropdownListWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.DropdownPopupWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.DropdownWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.EntityWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.FadingWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.FileChooserWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.FireWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.FlexibleContentEntryDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.FlexibleContentWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.FoldingWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.GridWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.HealthStatusWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.HorizontalListEntryDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.HorizontalListWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.HrWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.HudWidgetWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.HueSelectorWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.IconSliderNavigationButtonWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.IconSliderNavigationWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.IconSliderWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.IconWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.InterpolateWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ItemStackPickerWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ItemStackWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.KeybindWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.LabeledWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.LazyGridFeedWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.LazyGridWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ListWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.LiveServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.MarkdownWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.MarkerWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ModelWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.MultiKeybindWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.NavigationElementWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.NumberTextFieldWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.OverlayContentWrapperWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.OverlayWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.PageWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.PopupWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ProgressBarWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ProgressableProgressBarWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.RatingWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ScreenRendererWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ScrollWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ScrollbarWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SegmentDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SelectionWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SelectorWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ServerEntryWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ServerListWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SessionedListWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SettingOpenActivityWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SettingWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.ShadeSelectorWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SimpleButtonWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SimpleWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SliderWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SplitContentWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.StyledWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.SwitchWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TabLayoutWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TabWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TagInputWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TagTextFieldWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TextFieldWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TileWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TilesGridFeedWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TilesGridWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.TreeWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.VariableIconWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.VerticalListWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.WheelWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.WidgetFieldWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.WrappedListWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.api.lss.properties.direct.WrappedWidgetDirectPropertyValueAccessor;

/* JADX INFO: loaded from: LabyMod-4.jar:net/labymod/autogen/api/lss/ApiLabymod4DirectPropertyValueAccessorRegisterBulk.class */
public final class ApiLabymod4DirectPropertyValueAccessorRegisterBulk implements DirectPropertyValueAccessorRegisterBulk {
    @Override // net.labymod.api.client.gui.lss.property.DirectPropertyValueAccessorRegisterBulk
    public void register(Map<Class<? extends Widget>, DirectPropertyValueAccessor> map) {
        map.put(StyledWidget.class, new StyledWidgetDirectPropertyValueAccessor());
        map.put(AbstractWidget.class, new AbstractWidgetDirectPropertyValueAccessor());
        map.put(SimpleWidget.class, new SimpleWidgetDirectPropertyValueAccessor());
        map.put(TabWidget.class, new TabWidgetDirectPropertyValueAccessor());
        map.put(PageWidget.class, new PageWidgetDirectPropertyValueAccessor());
        map.put(NavigationElementWidget.class, new NavigationElementWidgetDirectPropertyValueAccessor());
        map.put(ListWidget.class, new ListWidgetDirectPropertyValueAccessor());
        map.put(HorizontalListWidget.class, new HorizontalListWidgetDirectPropertyValueAccessor());
        map.put(TabLayoutWidget.class, new TabLayoutWidgetDirectPropertyValueAccessor());
        map.put(CheckBoxWidget.class, new CheckBoxWidgetDirectPropertyValueAccessor());
        map.put(SliderWidget.class, new SliderWidgetDirectPropertyValueAccessor());
        map.put(TextFieldWidget.class, new TextFieldWidgetDirectPropertyValueAccessor());
        map.put(KeybindWidget.class, new KeybindWidgetDirectPropertyValueAccessor());
        map.put(SwitchWidget.class, new SwitchWidgetDirectPropertyValueAccessor());
        map.put(NumberTextFieldWidget.class, new NumberTextFieldWidgetDirectPropertyValueAccessor());
        map.put(MultiKeybindWidget.class, new MultiKeybindWidgetDirectPropertyValueAccessor());
        map.put(WrappedListWidget.class, new WrappedListWidgetDirectPropertyValueAccessor());
        map.put(TagInputWidget.class, new TagInputWidgetDirectPropertyValueAccessor());
        map.put(TagInputWidget.TagTextFieldWidget.class, new TagTextFieldWidgetDirectPropertyValueAccessor());
        map.put(ColorPickerSelectorWidget.class, new ColorPickerSelectorWidgetDirectPropertyValueAccessor());
        map.put(SessionedListWidget.class, new SessionedListWidgetDirectPropertyValueAccessor());
        map.put(VerticalListWidget.class, new VerticalListWidgetDirectPropertyValueAccessor());
        map.put(ColorPickerOverlayWidget.class, new ColorPickerOverlayWidgetDirectPropertyValueAccessor());
        map.put(FlexibleContentWidget.class, new FlexibleContentWidgetDirectPropertyValueAccessor());
        map.put(ColorPickerInputWidget.class, new ColorPickerInputWidgetDirectPropertyValueAccessor());
        map.put(ColorPickerInputWrapperWidget.class, new ColorPickerInputWrapperWidgetDirectPropertyValueAccessor());
        map.put(MarkerWidget.class, new MarkerWidgetDirectPropertyValueAccessor());
        map.put(SelectorWidget.class, new SelectorWidgetDirectPropertyValueAccessor());
        map.put(ShadeSelectorWidget.class, new ShadeSelectorWidgetDirectPropertyValueAccessor());
        map.put(SelectorWidget.class, new SelectorWidgetDirectPropertyValueAccessor());
        map.put(HueSelectorWidget.class, new HueSelectorWidgetDirectPropertyValueAccessor());
        map.put(AlphaSelectorWidget.class, new AlphaSelectorWidgetDirectPropertyValueAccessor());
        map.put(ColorPickerPlateWidget.class, new ColorPickerPlateWidgetDirectPropertyValueAccessor());
        map.put(OverlayWidget.class, new OverlayWidgetDirectPropertyValueAccessor());
        map.put(ColorPickerWidget.class, new ColorPickerWidgetDirectPropertyValueAccessor());
        map.put(WidgetFieldWidget.class, new WidgetFieldWidgetDirectPropertyValueAccessor());
        map.put(ItemStackPickerWidget.class, new ItemStackPickerWidgetDirectPropertyValueAccessor());
        map.put(DivWidget.class, new DivWidgetDirectPropertyValueAccessor());
        map.put(SimpleButtonWidget.class, new SimpleButtonWidgetDirectPropertyValueAccessor());
        map.put(ButtonWidget.class, new ButtonWidgetDirectPropertyValueAccessor());
        map.put(DropdownEntryWidget.class, new DropdownEntryWidgetDirectPropertyValueAccessor());
        map.put(DropdownListWidget.class, new DropdownListWidgetDirectPropertyValueAccessor());
        map.put(DropdownPopupWidget.class, new DropdownPopupWidgetDirectPropertyValueAccessor());
        map.put(DropdownWidget.class, new DropdownWidgetDirectPropertyValueAccessor());
        map.put(AdvancedSelectionWidget.class, new AdvancedSelectionWidgetDirectPropertyValueAccessor());
        map.put(FileChooserWidget.class, new FileChooserWidgetDirectPropertyValueAccessor());
        map.put(OverlayWidget.OverlayContentWrapperWidget.class, new OverlayContentWrapperWidgetDirectPropertyValueAccessor());
        map.put(MarkdownWidget.class, new MarkdownWidgetDirectPropertyValueAccessor());
        map.put(TilesGridWidget.class, new TilesGridWidgetDirectPropertyValueAccessor());
        map.put(TreeWidget.class, new TreeWidgetDirectPropertyValueAccessor());
        map.put(LazyGridWidget.class, new LazyGridWidgetDirectPropertyValueAccessor());
        map.put(LazyGridFeedWidget.class, new LazyGridFeedWidgetDirectPropertyValueAccessor());
        map.put(LazyGridWidget.class, new LazyGridWidgetDirectPropertyValueAccessor());
        map.put(WrappedListWidget.class, new WrappedListWidgetDirectPropertyValueAccessor());
        map.put(HorizontalListWidget.class, new HorizontalListWidgetDirectPropertyValueAccessor());
        map.put(ListWidget.class, new ListWidgetDirectPropertyValueAccessor());
        map.put(VerticalListWidget.class, new VerticalListWidgetDirectPropertyValueAccessor());
        map.put(FoldingWidget.class, new FoldingWidgetDirectPropertyValueAccessor());
        map.put(GridWidget.class, new GridWidgetDirectPropertyValueAccessor());
        map.put(TilesGridFeedWidget.class, new TilesGridFeedWidgetDirectPropertyValueAccessor());
        map.put(WrappedWidget.class, new WrappedWidgetDirectPropertyValueAccessor());
        map.put(FlexibleContentEntry.class, new FlexibleContentEntryDirectPropertyValueAccessor());
        map.put(HorizontalListEntry.class, new HorizontalListEntryDirectPropertyValueAccessor());
        map.put(TileWidget.class, new TileWidgetDirectPropertyValueAccessor());
        map.put(SplitContentWidget.class, new SplitContentWidgetDirectPropertyValueAccessor());
        map.put(ScrollWidget.class, new ScrollWidgetDirectPropertyValueAccessor());
        map.put(LabeledWidget.class, new LabeledWidgetDirectPropertyValueAccessor());
        map.put(FlexibleContentWidget.class, new FlexibleContentWidgetDirectPropertyValueAccessor());
        map.put(ScrollbarWidget.class, new ScrollbarWidgetDirectPropertyValueAccessor());
        map.put(IconSliderWidget.class, new IconSliderWidgetDirectPropertyValueAccessor());
        map.put(IconSliderWidget.IconSliderNavigationWidget.class, new IconSliderNavigationWidgetDirectPropertyValueAccessor());
        map.put(IconSliderWidget.IconSliderNavigationButtonWidget.class, new IconSliderNavigationButtonWidgetDirectPropertyValueAccessor());
        map.put(DivWidget.class, new DivWidgetDirectPropertyValueAccessor());
        map.put(AdvancedPopupWidget.class, new AdvancedPopupWidgetDirectPropertyValueAccessor());
        map.put(ItemStackWidget.class, new ItemStackWidgetDirectPropertyValueAccessor());
        map.put(FireWidget.class, new FireWidgetDirectPropertyValueAccessor());
        map.put(HealthStatusWidget.class, new HealthStatusWidgetDirectPropertyValueAccessor());
        map.put(EntityWidget.class, new EntityWidgetDirectPropertyValueAccessor());
        map.put(InterpolateWidget.class, new InterpolateWidgetDirectPropertyValueAccessor());
        map.put(FadingWidget.class, new FadingWidgetDirectPropertyValueAccessor());
        map.put(PopupWidget.class, new PopupWidgetDirectPropertyValueAccessor());
        map.put(HudWidgetWidget.class, new HudWidgetWidgetDirectPropertyValueAccessor());
        map.put(ModelWidget.class, new ModelWidgetDirectPropertyValueAccessor());
        map.put(ActivitySettingWidget.class, new ActivitySettingWidgetDirectPropertyValueAccessor());
        map.put(SettingWidget.class, new SettingWidgetDirectPropertyValueAccessor());
        map.put(SettingOpenActivityWidget.class, new SettingOpenActivityWidgetDirectPropertyValueAccessor());
        map.put(CategoryWidget.class, new CategoryWidgetDirectPropertyValueAccessor());
        map.put(AddonActivityWidget.class, new AddonActivityWidgetDirectPropertyValueAccessor());
        map.put(CollectionResetWidget.class, new CollectionResetWidgetDirectPropertyValueAccessor());
        map.put(SelectionWidget.class, new SelectionWidgetDirectPropertyValueAccessor());
        map.put(ServerListWidget.class, new ServerListWidgetDirectPropertyValueAccessor());
        map.put(ServerEntryWidget.class, new ServerEntryWidgetDirectPropertyValueAccessor());
        map.put(ServerInfoWidget.class, new ServerInfoWidgetDirectPropertyValueAccessor());
        map.put(LiveServerInfoWidget.class, new LiveServerInfoWidgetDirectPropertyValueAccessor());
        map.put(ServerInfoWidget.class, new ServerInfoWidgetDirectPropertyValueAccessor());
        map.put(Document.class, new DocumentDirectPropertyValueAccessor());
        map.put(ChatLineWidget.class, new ChatLineWidgetDirectPropertyValueAccessor());
        map.put(ChatTabWidget.class, new ChatTabWidgetDirectPropertyValueAccessor());
        map.put(ChatButtonWidget.class, new ChatButtonWidgetDirectPropertyValueAccessor());
        map.put(RatingWidget.class, new RatingWidgetDirectPropertyValueAccessor());
        map.put(ComponentWidget.class, new ComponentWidgetDirectPropertyValueAccessor());
        map.put(WheelWidget.class, new WheelWidgetDirectPropertyValueAccessor());
        map.put(WheelWidget.Segment.class, new SegmentDirectPropertyValueAccessor());
        map.put(ContextMenuListWidget.class, new ContextMenuListWidgetDirectPropertyValueAccessor());
        map.put(ContextMenuEntryWidget.class, new ContextMenuEntryWidgetDirectPropertyValueAccessor());
        map.put(IconWidget.class, new IconWidgetDirectPropertyValueAccessor());
        map.put(ScreenRendererWidget.class, new ScreenRendererWidgetDirectPropertyValueAccessor());
        map.put(HrWidget.class, new HrWidgetDirectPropertyValueAccessor());
        map.put(VariableIconWidget.class, new VariableIconWidgetDirectPropertyValueAccessor());
        map.put(ProgressBarWidget.class, new ProgressBarWidgetDirectPropertyValueAccessor());
        map.put(ProgressableProgressBarWidget.class, new ProgressableProgressBarWidgetDirectPropertyValueAccessor());
        map.put(AttachmentWidget.class, new AttachmentWidgetDirectPropertyValueAccessor());
        map.put(AbstractWidget.class, new AbstractWidgetDirectPropertyValueAccessor());
        map.put(WrappedWidget.class, new WrappedWidgetDirectPropertyValueAccessor());
        map.put(ChatMessagesWidget.class, new ChatMessagesWidgetDirectPropertyValueAccessor());
    }
}
